Remove feature_dehydration
element-hq/matrix-react-sdk pull request #138
Opened 2024-10-09 16:03 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] I have licensed the changes to Element by completing the [Contributor License Agreement (CLA)](https://cla-assistant.io/element-hq/matrix-react-sdk)

https://github.com/matrix-org/matrix-spec-proposals/pull/2697 is abandoned
The old dehydration feature is deprecated and not implemented in the rust crypto.

2024-10-09 16:47 UTC, dbkr approved these changes

2024-10-09 19:12 UTC, uhoreg requested changes

2024-10-09 19:12 UTC, uhoreg commented on src/SecurityManager.ts
> +            if (!keyId) {
This whole `if` statement is related to dehydration, so can be removed completely -- the remaining branches are just logging, explaining why it isn't setting a decryption key

2024-10-09 19:12 UTC, uhoreg commented on src/Lifecycle.ts
The `hydrateSession` function also needs to be removed (along with the two places where it's called).

2024-10-09 19:12 UTC, uhoreg commented on src/SecurityManager.ts
> +            if (!keyId) {
which means `keyId` can also be removed, since it isn't being used for anything else

2024-10-10 08:08 UTC, florianduros commented on src/components/structures/auth/SoftLogout.tsx
> +            this.props.onTokenLoginCompleted();
`onTokenLoginCompleted` is not optional in the type declaration.

2024-10-10 17:30 UTC, uhoreg approved these changes

2024-10-14 16:33 UTC, merged